title: Preacher
description: automation done simple and super fast 
theme: just-the-docs

url: https://trpouh.github.io/preacher

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
