[package]
edition = "2021"
name = "preacher"
version = "0.1.0"

[dependencies]
clap = {version = "4.0.26", features = ["derive"]}

serde = { version = "1.0.126", features = ["derive"] }

serde_yaml = "0.9.14"