[package]
name = "psalmer"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.7"
syn = {version = "1.0.52", features = ["full", "extra-traits"]}
serde = {version = "1.0.126", features = ["derive"]}